config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For devise

  # devise_for :deviseusers

  # devise_scope :deviceuser do
  #   get '/users', to: 'devise/registrations#new'
  #   get '/users/password', to: 'devise/passwords#new'
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }


 get 'storys', to: 'storys#index'
   delete 'delete/story', to:'storys#delete', as: 'delete_story'
   post 'create/story', to:'storys#create', as:'new_story'
   get 'add/story', to:"storys#new", as:"add_story"

  get 'allusers', to: 'friends#index'
  get 'allusers/following', to: 'friends#following'
  get 'allusers/followers', to: 'friends#followers'
  post 'friends/Following', to: 'friends#create', as: 'set_follow'
    delete 'friends/unFollowing', to: 'friends#destroy', as: 'set_unfollow'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  delete 'posts/like/delete', to: 'likes#destroyPostLike', as:'post_unlike'
  post 'posts/like/create', to: 'likes#createLikeForPost', as:'post_like'

  post 'comments/like/create', to: 'likes#createLikeForComment', as:'comment_like'
  post 'comments/like/delete', to: 'likes#deleteCommentLike', as:'comment_unlike'

  # Defines the root path route ("/")
  # For group
  get 'groups', to:'groups#show'
  get 'groups/new' , to:'groups#new'
  get 'groups/mygroups' , to:'groups#mygroups'
  post 'groups/new/create' , to:'groups#create', as:'new_group'
  post 'groups/addUser', to:'members#create', as:'add_to_group'
  post 'groups/deleteGroups', to:'groups#delete', as:'delete_group'
  get 'groups/:id/view', to: 'groups#view', as:'view_group'
  get 'groups/join', to: 'groups#join', as:'join_group'



  # get 'groups/mygroups', to:'groups#mygroup'

  root "posts#index"
  resources :likes, only: [:create, :destroy]
  resources :posts do
    resources :comments
  end

  # get 'posts/:postid/comment/:id/', to:'memb'

  resources :users do
    resources :likes
  end
  resources :storys


  # for notifications
    get 'notifications/all', to: 'notifications#view', as:'notifications_all'
    post 'notifications/markasread', to:'notifications#markAsRead', as:'notifications_mark_as_read'



# ``````````````````````````````api start``````````````````````````````````````````````````````
    # For api
    namespace :api ,default: {format: :json} do
      devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For devise

  # devise_for :deviseusers

  # devise_scope :deviceuser do
  #   get '/users', to: 'devise/registrations#new'
  #   get '/users/password', to: 'devise/passwords#new'
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }


 get 'storys', to: 'storys#index'
   delete 'delete/story/:id', to:'storys#delete', as: 'delete_story'
   post 'create/story', to:'storys#create', as:'new_story'
   get 'add/story', to:"storys#new", as:"add_story"

  get 'allusers', to: 'friends#index'
  get 'allusers/following', to: 'friends#following'
  get 'allusers/followers', to: 'friends#followers'
  post 'friends/Following', to: 'friends#create', as: 'set_follow'
  delete 'friends/unFollowing/:id', to: 'friends#destroy', as: 'set_unfollow'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  delete 'posts/like/delete', to: 'likes#destroyPostLike', as:'post_unlike'
  post 'posts/like/create', to: 'likes#createLikeForPost', as:'post_like'

  post 'comments/like/create', to: 'likes#createLikeForComment', as:'comment_like'
  post 'comments/like/delete', to: 'likes#deleteCommentLike', as:'comment_unlike'

  # Defines the root path route ("/")
  # For group
  get 'groups', to:'groups#show'
  post 'groups/new/create' , to:'groups#create', as:'new_group'
  delete 'groups/deleteGroups/:group_id', to:'groups#delete', as:'delete_group'



  # get 'groups/mygroups', to:'groups#mygroup'
  #custom api
  root "posts#index"

  get 'posts/zerolikes', to: 'posts#postWithZeroLike', as:'post_zerolike'
  get 'posts/mostlikes', to: 'posts#postWithMoreLikes', as:'post_mostlike'
  get 'posts/mostComments', to: 'posts#postWithMoreComments', as:'post_mostComments'
  get 'users/morePosts', to:'posts#userWithMorePost', as:'user_morePosts'
  get 'groups/mostgroups', to: 'groups#userWithMoreGroups', as:'user_mostGroups'

  resources :likes, only: [:create, :destroy]
  resources :posts do
    resources :comments
  end

  # get 'posts/:postid/comment/:id/', to:'memb'

  resources :users do
    resources :likes
  end
  resources :storys


  # for notifications
    get 'notifications/all', to: 'notifications#view', as:'notifications_all'
    post 'notifications/markasread', to:'notifications#markAsRead', as:'notifications_mark_as_read'


    end
    # end for api

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :likes ,as: :likeable,dependent: :destroy
  validates :comment,presence: true, length: { minimum: 2, maximum: 30}
  
   scope :likes_greater_than_one, -> {
    joins("LEFT JOIN (SELECT likeable_id, COUNT(id) AS count_likes FROM likes WHERE likeable_type = 'Comment' GROUP BY likeable_id) subquery ON subquery.likeable_id = comments.id")
    .select('comments.*, subquery.count_likes')
    .where('subquery.count_likes > ?', 1)
  }
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < Api::ApiController
  before_action :is_comment_owner, only: [:edit,:update]
  before_action :is_registered_user
  before_action :is_post_owner,only: [:destroy]

  def index
    post = Post.find_by(id: params[:post_id])
    if post
        comments = post.comments.all
        unless comments.empty?
           render json: comments, status: :found
        else
            render json: {message: "unable to fetch comments"}, status: :not_found
        end
    else
         render json: {message: "no post found"}, status: :not_found
    end
  end



def update
    user = User.find_by(id:current_user.id)
    post = Post.find_by(id: params[:post_id] )

    if post == nil or user==nil
        render json: {message:"no user or post found"},status: :not_found
    else
        comment = post.comments.find_by(id: params[:id])
        if comment
          if comment.update(comment_params)
              render json: comment, status: :ok
          else
              render json: {message:comment.errors.full_messages},status: :unprocessable_entity
          end
        else
          render json: {message: "no comment found"}, status: :not_found
        end
    end
end

  def create


    user = User.find_by(id:current_user.id)
    post = Post.find_by(id: params[:post_id] )

    if post == nil or user==nil
        render json: {message:"no user or post found"},status: :not_found
    else
        param =  params.require(:comment)
        comment = Comment.new(commenter: param[:commenter], comment: param[:comment], user_id: user.id)
        post.comments << comment
        if  comment.save
          if post.save
              render json: comment, status: :created
          else
              render json: {message:post.errors.full_messages},status: :unprocessable_entity
          end
        else
          render json: {message:comment.errors.full_messages},status: :unprocessable_entity
        end
    end
  end


   def destroy
    post = Post.find_by(id:params[:post_id])
    if post
      comment = post.comments.find_by(id:params[:id])
      if comment
         if comment.destroy
            render json: {message:"comment deleted"}, status: :see_other
         else
            render json: {message:comment.errors.full_messages},status: :unprocessable_entity
         end
      else
        render json: {message:"no commnents found"}, status: :not_found
      end
    else
        render json: {message:"No post found"}, status: :not_found
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :comment)
    end

    def is_comment_owner
      comment = Comment.find_by(id:params[:id])
      unless comment and current_user and  current_user == comment.user
          render json:{message:"only owner can update or delete"},status: :forbidden
      end
    end

    def is_post_owner

      comment = Comment.find_by(id:params[:id])
      unless (user_signed_in? and current_user == comment.post.user) or (current_user == comment.user)
          flash[:notice] = "Unauthorized access"
          render json: {messge: "only registered users can access comments"},status: :unauthorized
      end
    end

    def is_registered_user
      unless current_user
        render json: {messge: "only registered users can access comments"},status: :unauthorized
      end
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_comment_owner, only: [:edit,:update]
  before_action :is_post_owner, only:[:destroy]

  def edit
    @post = Post.find_by(id:params[:post_id])
    if @post
        @comment = @post.comments.find_by(id:params[:id])
    end
    unless @post and @comment
      redirect_to root_path
    end
  end

  def update

    @post = Post.find_by(id:params[:post_id])
    @comment = @post.comments.find_by(id:params[:id])
    if @comment.update(comment_params)
      flash[:updateSuccess] = "created.."
      redirect_to  post_path(params[:post_id])
    else
      render :edit, status: :unprocessable_entity
    end

  end

   def create
    @user = User.find_by(id:current_user.id)
    @post = Post.find_by(id: params[:post_id])
    if @post == nil
      redirect_to root_path
    else
      param =  params.require(:comment)
      @comment = Comment.new(commenter: param[:commenter], comment: param[:comment], user_id: @user.id)
      @post.comments << @comment
      if @comment.save
        @post.save
      else
        flash[:createError] = "unable to create"
        flash[:error] = "comment" + @comment.errors[:comment][0]
      end
      flash[:createSuccess] = "created.."
      redirect_to post_path(:post_id)
    end



  end

   def destroy
    @post = Post.find_by(id:params[:post_id])
    if @post == nil
      redirect_to root_path
    else
      @comment = @post.comments.find_by(id:params[:id])
      if @comment.destroy
        flash[:deleteSuccess] = "deleted.."
      else
        flash[:deletefailure] = "unable to delete.."
      end
      redirect_to post_path(:post_id)
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :comment)
    end

    def is_comment_owner

      @comment = Comment.find_by(id: params[:id])

      unless @comment and user_signed_in? and current_user == @comment.user

          flash[:notice] = "Unauthorized access"
          redirect_to root_path
      end
    end

    def is_post_owner
      @comment = Comment.find_by(id:params[:id])
      unless (user_signed_in? and current_user.id == @comment.post.user.id) or (current_user.id == @comment.user.id)
          flash[:notice] = "Unauthorized access"
          redirect_to root_path
      end
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<% stylesheet_link_tag "commentsForm"%>

<%= form_with model:[ post, post.comments.build ],url:post_comments_path(post) do |form| %>
  <p>

    <%= form.text_field :commenter,value: current_user.name , type: "hidden"  %>
  </p>

  <p>
    <span>
        <%= form.text_field :comment, placeholder:"Add a new comment",class:"commentInput", required: true %>
    </span>
    <span>
       <% post.errors.full_messages_for(:comment).each do |message| %>
      <div><%= message %></div>
    <% end %>
      </span>
    <span>
       <%= button_tag type: :submit, class:"commentSubmit"  do %>
           <span class="material-symbols-outlined commentSubmitButton">
                  send
            </span>
      <% end %>
    </span>
  </p>

<% end %>

app/views/comments/_show.html.erb
<%= stylesheet_link_tag 'commentsShow' %>


<%  post.comments.each do |comment| %>
  <% if comment.id %>
    <div class="eachComment d-flex">
        <div  class="d-flex gap-2">
            <div>
            <i class="fa-solid fa-user  "></i>
            </div>
            <div class="commentName commenterName">
                  <%= comment.commenter %>
            </div>
            <div class="commentContent  ">
              <%= comment.comment %>
            </div>
        </div>
        <div class="right d-flex gap-2" >
            <div class="d-flex">
                <div >
                  <% like = comment.likes.where(user_id:1)%>

                  <% if like.length == 0%>
                       <%= button_to comment_like_path, params: {comment_id: comment.id, post_id: post.id}, class:"likesButton",method: :post, class:'likesButton'  do %>
                            <i class="fa-regular fa-heart "></i>
                        <% end %>
                  <%else%>
                        <%= button_to   comment_unlike_path, params: {comment_id: comment.id,post_id:post.id, like_id: like[0].id }, method: :post, class:'likesButton'   do %>
                            <i class="fa-solid fa-heart "></i>
                        <%end%>
                 <% end %>
                 </div>
                 <div>
                 <%= comment.likes.count %>
                  </div>
            </div>
            <% if comment.user.id == current_user.id || comment.post.user.id == current_user.id%>

            <% if comment.user.id == current_user.id  %>
            <div class="commentRight">

                  <%= link_to  edit_post_comment_path(post_id:post, id:comment),method: :get  do %>
                    <i class="fa-regular fa-pen-to-square"></i>
                  <%end%>

            </div>
            <% end %>
            <div>
                  <%= link_to   [comment.post, comment],class:"editDelete", data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                   }  do %>
                                   <i class="fa-solid fa-trash" style="color: #ec0936;"></i>
                  <%end%>
            </div>


            <% end %>

        </div>


    </div>
    <hr>
<% end %>
<% end %>









<%# ```````````````````````````````````` %>
<% if false %>

<h2>Comments</h2>
<%  post.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.comment %>
  </p>
  <% like = comment.likes.where(user_id:1)%>

  <% if like.length == 0%>
  <%= button_to "like", comment_like_path, params: {comment_id: comment.id}, method: :post %>
  <%else%>

  <%= button_to "UnLike", comment_unlike_path ,params: {comment_id: comment.id, like_id: like[0].id }, method: :post %>
  <% end %>

    COMMENTS:  <%= comment.likes.count %>
    <hr>

  <p>
    <%= link_to "Destroy", [comment.post, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  </p>
  <br>
  <%= link_to  "Edit", edit_post_comment_path(post, comment) %>
  <p>``````````````````````````</p>
<% end %>


<% end %>

app/views/comments/edit.html.erb
<div>
  <br>
<h1>EDIT</h1>
<%= form_with class:"form-group bg-light text-dark w-50 mx-auto mt-5 p-5", model: [ @post, @comment ] do |form| %>
  <p>

    <%= form.text_field :commenter,value: current_user.name , type: "hidden"  %>
  </p>
  <p>
    <%= form.label :comment,class:"form-label" %><br>
    <%= form.text_area :comment,class:"form-control"  %>
  </p>
  <p>
    <%= form.submit class:"btn btn-primary" %>
  </p>
<% end %>
</div>