config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For devise

  # devise_for :deviseusers

  # devise_scope :deviceuser do
  #   get '/users', to: 'devise/registrations#new'
  #   get '/users/password', to: 'devise/passwords#new'
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }


 get 'storys', to: 'storys#index'
   delete 'delete/story', to:'storys#delete', as: 'delete_story'
   post 'create/story', to:'storys#create', as:'new_story'
   get 'add/story', to:"storys#new", as:"add_story"

  get 'allusers', to: 'friends#index'
  get 'allusers/following', to: 'friends#following'
  get 'allusers/followers', to: 'friends#followers'
  post 'friends/Following', to: 'friends#create', as: 'set_follow'
    delete 'friends/unFollowing', to: 'friends#destroy', as: 'set_unfollow'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  delete 'posts/like/delete', to: 'likes#destroyPostLike', as:'post_unlike'
  post 'posts/like/create', to: 'likes#createLikeForPost', as:'post_like'

  post 'comments/like/create', to: 'likes#createLikeForComment', as:'comment_like'
  post 'comments/like/delete', to: 'likes#deleteCommentLike', as:'comment_unlike'

  # Defines the root path route ("/")
  # For group
  get 'groups', to:'groups#show'
  get 'groups/new' , to:'groups#new'
  get 'groups/mygroups' , to:'groups#mygroups'
  post 'groups/new/create' , to:'groups#create', as:'new_group'
  post 'groups/addUser', to:'members#create', as:'add_to_group'
  post 'groups/deleteGroups', to:'groups#delete', as:'delete_group'
  get 'groups/:id/view', to: 'groups#view', as:'view_group'
  get 'groups/join', to: 'groups#join', as:'join_group'



  # get 'groups/mygroups', to:'groups#mygroup'

  root "posts#index"
  resources :likes, only: [:create, :destroy]
  resources :posts do
    resources :comments
  end

  # get 'posts/:postid/comment/:id/', to:'memb'

  resources :users do
    resources :likes
  end
  resources :storys


  # for notifications
    get 'notifications/all', to: 'notifications#view', as:'notifications_all'
    post 'notifications/markasread', to:'notifications#markAsRead', as:'notifications_mark_as_read'



# ``````````````````````````````api start``````````````````````````````````````````````````````
    # For api
    namespace :api ,default: {format: :json} do
      devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For devise

  # devise_for :deviseusers

  # devise_scope :deviceuser do
  #   get '/users', to: 'devise/registrations#new'
  #   get '/users/password', to: 'devise/passwords#new'
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }


 get 'storys', to: 'storys#index'
   delete 'delete/story/:id', to:'storys#delete', as: 'delete_story'
   post 'create/story', to:'storys#create', as:'new_story'
   get 'add/story', to:"storys#new", as:"add_story"

  get 'allusers', to: 'friends#index'
  get 'allusers/following', to: 'friends#following'
  get 'allusers/followers', to: 'friends#followers'
  post 'friends/Following', to: 'friends#create', as: 'set_follow'
  delete 'friends/unFollowing/:id', to: 'friends#destroy', as: 'set_unfollow'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  delete 'posts/like/delete', to: 'likes#destroyPostLike', as:'post_unlike'
  post 'posts/like/create', to: 'likes#createLikeForPost', as:'post_like'

  post 'comments/like/create', to: 'likes#createLikeForComment', as:'comment_like'
  post 'comments/like/delete', to: 'likes#deleteCommentLike', as:'comment_unlike'

  # Defines the root path route ("/")
  # For group
  get 'groups', to:'groups#show'
  post 'groups/new/create' , to:'groups#create', as:'new_group'
  delete 'groups/deleteGroups/:group_id', to:'groups#delete', as:'delete_group'



  # get 'groups/mygroups', to:'groups#mygroup'
  #custom api
  root "posts#index"

  get 'posts/zerolikes', to: 'posts#postWithZeroLike', as:'post_zerolike'
  get 'posts/mostlikes', to: 'posts#postWithMoreLikes', as:'post_mostlike'
  get 'posts/mostComments', to: 'posts#postWithMoreComments', as:'post_mostComments'
  get 'users/morePosts', to:'posts#userWithMorePost', as:'user_morePosts'
  get 'groups/mostgroups', to: 'groups#userWithMoreGroups', as:'user_mostGroups'

  resources :likes, only: [:create, :destroy]
  resources :posts do
    resources :comments
  end

  # get 'posts/:postid/comment/:id/', to:'memb'

  resources :users do
    resources :likes
  end
  resources :storys


  # for notifications
    get 'notifications/all', to: 'notifications#view', as:'notifications_all'
    post 'notifications/markasread', to:'notifications#markAsRead', as:'notifications_mark_as_read'


    end
    # end for api

end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  belongs_to :community
  has_and_belongs_to_many :members, dependent: :destroy
  validates :name, presence: true,  length: { minimum: 2,maximum: 20}
  validates :bio, presence: true,  length: { minimum: 2,maximum: 20}

  scope :group_with_community_one, -> {
   where('community_id == ?', 1)
  }

end

app/controllers/api/groups_controller.rb
class Api::GroupsController < Api::ApiController
    before_action :is_registered_user, only: [:new,:create,:mygroups,:view]
      before_action :is_group_owner, only: [:delete]
  def show
    groups = Group.all
    if groups
       render json: groups, status: :ok
    else
       render json: {message:"no group found"}, status: :not_found
    end
  end

  def create
    community = Community.find_by(id:params.require(:group)[:category])
    user = User.find_by(id:current_user.id)
    if community and user
      group = Group.new(name:params.require(:group)[:name], bio:params.require(:group)[:bio])
      user.groups << group
      community.groups << group
      if group.save
        if user.save
          if community.save
              render json: {message:"group created"}, status: :created
          else
            render json: {message:community.errors.full_messages},status: :unprocessable_entity
          end
        else
          render json: {message:user.errors.full_messages},status: :unprocessable_entity
        end
      else
        render json: {message:group.errors.full_messages},status: :unprocessable_entity
      end
    else
      render json: {message:"no user or community"}, status: :not_found
    end

  end

  def delete

    group = Group.find_by(id:params[:group_id])
    if group
      if group.destroy
         render json: {message:"group deleted"}, status: :see_other
      else
         render json: {message:group.errors.full_messages},status: :unprocessable_entity
      end
    else
      render json: {message:"unable to find group"}, status: :not_found
    end

  end
  def userWithMoreGroups

    user_with_most_groups = User.joins(:groups)
                              .group(:id)
                              .order('COUNT(groups.id) DESC')
                              .limit(1)
                              .first
    if user_with_most_groups
       render json: user_with_most_groups,status: :ok
    else
      render json: {message:"unable to fetch"},status: :not_found
    end

  end
  private
    def is_group_owner
      group = Group.find_by(params[:group_id])
      unless current_user and current_user == group.user
          render json: {messge: "only group owner can delete"},status: :forbidden
      end
    end

     def is_registered_user
      unless current_user
        render json: {messge: "only registered users can access groups"},status: :unauthorized
      end
    end


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    before_action :authenticate_user!, only: [:new,:create,:delete,:mygroups,:join,:view]
    before_action :is_group_owner, only: [:delete]

  def show
    @groups = Group.all
  end
  def new
    @communitys = Community.all
    @group = Group.new
  end
  def create
    @communitys = Community.all
    @community = Community.find_by(id:params.require(:group)[:category])
    if @community == nil
      redirect_to root_path
    else
      @user = User.find_by(id:current_user.id)
      @group = Group.new(name:params.require(:group)[:name], bio:params.require(:group)[:bio])
      @user.groups << @group
      @community.groups << @group
      if @group.save
        @user.save
        @community.save
        redirect_to groups_path
      else
        render :new, status: :unprocessable_entity
      end
    end

  end

  def mygroups

    @members = Member.all.where(user_id:User.find(current_user.id))

  end

  def delete
    @group = Group.find_by(id:params[:group_id])
    if @group and @group.destroy
      redirect_to groups_mygroups_path
    else
      redirect_to root_path
    end
  end

  def view
    @group = Group.find_by(id:params[:id])
    if @group == nil
      redirect_to root_path
    end

  end

  def join

   @group = Group.find_by(id:params[:group_id])
    if @group == nil
      redirect_to root_path
    end
  end

  private
    def is_group_owner
      @group = Group.find_by(id:params[:group_id])
      unless @group and user_signed_in? and current_user.id == @group.user.id
          flash[:notice] = "Unauthorized access"
          redirect_to root_path
      end
    end


end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_groupPosts.html.erb
<%= stylesheet_link_tag 'postsIndex' %>



<div class="row postParent bg-light" >

<% posts = Post.all%>
<% posts.each do |post| %>
<% memberCheck = Group.find(group.id).members.where(user_id:post.user.id) %>
<% if memberCheck.length == 0 %>
<%next%>
<% end %>
<%# Checking for privacy %>
<%if user_signed_in? == false and post.privacy=="Private"%>

<% next %>

<% end %>

<% if user_signed_in? and post.privacy == "Private" and  post.user.id != current_user.id%>


<% friend = Friend.where(fromUser: post.user.id, toUser: current_user.id )  %>

  <% if friend.length == 0 %>

      <% next%>
  <% end %>
<% end %>


<div class ="row" style="justify-content:center">
<div class="card mb-3 col-md-6   text-dark">
  <div class="card-header row">
    <h5 class="card-title col-md-6">
            <i class="fa-solid fa-user  "></i>
             <%= post.user.name%></h5>
    <h5 class="card-title col-md-6 ">
 <%= link_to   post do %>
 <button type="button" class="btn btn-primary float-md-end">View</button>

 <%end%>
  </h5>

  </div>
  <div class="card-body">
    <h6 class="card-subtitle mb-2 text-muted"><%= post.title%></h6>


      <% post.images.each do |image|%>

      <%= image_tag(image ,class:'img-fluid' )%>
     <%end%>

    <p class="card-text"><%= post.description%></p>
    <hr>
    <div class="d-flex flex-row" >
      <% like = post.likes.where(user_id:1)%>
        <% if like.length == 0%>
            <%= button_to post_like_path, params: {post_id: post.id}, class:"likesButton",method: :post, class:'likesButton'  do %>
            <i class="fa-regular fa-heart likUnlikeIcon"></i>
            <%end%>
        <%else%>

            <%= button_to   post_unlike_path, params: {post_id: post.id, like_id: like[0].id }, method: :post, class:'likesButton'   do %>
            <i class="fa-solid fa-heart likUnlikeIcon"></i>
            <%end%>
        <% end %>

        <div class="post-info">
          <span class="likes-count"><i class="bi bi-heart-fill"></i> <%= post.likes.count %> Likes</span>
          <span class="comment-count"><i class="bi bi-chat-fill"></i>  <%= post.comments.count %> Comments</span>
        </div>
      </div>

  </div>
</div>




<%# ```````````````````````````` %>

<% if false %>

<div class ="row" style="justify-content:center">
<div class="col-md-6" >
    <h1>Title:</h1>

    <p> <%= post.title %><p>
    <h1>Description:</h1>

    <p> <%= post.description %><p>
    <%= link_to "View Post", post %>
    <p>

    <% post.images.each do |image|%>

      <%= image_tag(image, style: "object-fit: contain; width: 200px; height: 200px") %>


    <%end%>
  </p>
  <%= like = post.likes.where(user_id:1)%>

  <% if like.length == 0%>
  <%= button_to "like", post_like_path, params: {post_id: post.id}, method: :post %>
  <%else%>
  <%= like[0].id%>
   <%= button_to "UNlike", post_unlike_path, params: {post_id: post.id, like_id: like[0].id }, method: :post %>

  <% end %>

    LIKES:  <%= post.likes.count %>
    COMMENTS: <%= post.comments.count%>
    <hr>
</div>
</div>

<%end%>
<%# for if false %>

<%end %>
</div>

app/views/groups/_showGroups.html.erb
 <div class="col">
    <div class="card" style="width: 23rem;">
        <div class="card-body">
            <h5 class="card-title"> Name : <%= groupShow.name %> </h5>

            <p class="card-text">  Bio : <%= groupShow.bio %> </p>
            <p class="card-text">  Category : <%= groupShow.community.name %> </p>

            <div class="d-flex">
                <% if user_signed_in? %>
                    <% member = groupShow.members.where(user_id: current_user.id ) %>
                    <% if member.length == 0 && groupShow.user.id != current_user.id %>
                         <%= button_to "Join Group" , join_group_path, params: {group_id: groupShow.id}, method: :get , class:"btn btn-primary btn-sm mx-2" %>

                    <% end %>
                <% end %>

                <% if  user_signed_in? and current_user.id == groupShow.user.id %>
                    <div>
                    <%= button_to "Delete Group" , delete_group_path, params: {group_id: groupShow.id}, method: :post , class:"btn btn-danger btn-sm mx-2"%>

                    </div>
                <% end %>
                <div>
                <%= button_to "View Group" , view_group_path(id:groupShow.id), method: :get , class:"btn btn-success btn-sm mx-2"%>

                </div>
            </div>
        </div>
    </div>
</div>

app/views/groups/_showMember.html.erb
<% stylesheet_link_tag "friendsListFriend"%>
    <li class="list-group-item d-flex ">
        <div class="d-flex flex-column">
            <div>
                <i class="fa-solid fa-user"></i>
                <%= userName %>
            </div>
            <div>
                <%= userEmail %>
            </div>
        </div>
        <div class="button">
            <% if current_user.id != userId %>
         <%= render 'friends/follow' , touser:userId %>
         <% end%>
        </div>
    <br>
    </li>

app/views/groups/join.html.erb
     <div  >
                <div class="modal-dialog">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title mx-auto my-4" id="exampleModalLabel"> Join this group</h1>
                    </div>
                    <div class="modal-body">

                        <%= render "members/form" , groupJoin: @group %>
                    </div>

                    </div>
                </div>
                </div>

app/views/groups/mygroups.html.erb
<h1>My Group </h1>
<div class="row row-cols-1 row-cols-md-4 g-3">
<%  @members.each do |member|%>
<% groups = member.groups %>
<% groups.each do |group| %>
<%= render 'showGroups', groupShow: group %>
<% end %>

<% end %>
</div>

app/views/groups/new.html.erb
<h1>Creating a group
 </h1>
<%= form_with model: @group ,url:new_group_path , class:"bg-light text-dark story_form" do |form| %>
  <div>
    <%= form.label :name , class:"form-label" %>
    <%= form.text_field :name ,required: true, class:"form-control" %>
     <% @group.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
    <br>
    <%= form.label :bio , class:"form-label" %>
    <%= form.text_field :bio, required: true, class:"form-control"%>
     <% @group.errors.full_messages_for(:bio).each do |message| %>
      <div><%= message %></div>
    <% end %>
    <br>
    <%= form.label :category %>
    <%= form.collection_select :category, @communitys, :id, :category %>
    <%= form.submit "submit" , class:"btn btn-success w-100 mt-4" %>
  </div>
<% end %>

app/views/groups/show.html.erb
<%= stylesheet_link_tag 'groups' %>

<h1>ALL GROUPS</h1>
<div class="row row-cols-1 row-cols-md-4 g-3">

<% @groups.each do |group| %>

<%= render 'showGroups', groupShow:group%>

<%end%>

</div>

app/views/groups/view.html.erb
<div class="group">
    <br>
    <h1> <b> Group name: </b><%= @group.name %> </h1>
    <br>
    <h1> <b>Group Bio: </b><%= @group.bio %> </h1>
    <h1> <b>Group Admin: </b><%= @group.user.name %> </h1>
    <h1> <b>Group Category: </b><%= @group.community.name %> </h1>
</div>

<br>
<h1> MEMBERS:</h1>

<ul class="list-group list-group-flush followList">

    <% members = @group.members %>
        <% members.each do |member| %>

            <% user = User.find(member.user_id) %>
             <%= render "showMember", userName: user.name, userEmail: user.email, userId: user.id %>
    <% end %>

</ul>
<hr>
<h1>Members Posts</h1>
<ul>

<%= render "groupPosts", group:@group %>
</ul>