config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For devise

  # devise_for :deviseusers

  # devise_scope :deviceuser do
  #   get '/users', to: 'devise/registrations#new'
  #   get '/users/password', to: 'devise/passwords#new'
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }


 get 'storys', to: 'storys#index'
   delete 'delete/story', to:'storys#delete', as: 'delete_story'
   post 'create/story', to:'storys#create', as:'new_story'
   get 'add/story', to:"storys#new", as:"add_story"

  get 'allusers', to: 'friends#index'
  get 'allusers/following', to: 'friends#following'
  get 'allusers/followers', to: 'friends#followers'
  post 'friends/Following', to: 'friends#create', as: 'set_follow'
    delete 'friends/unFollowing', to: 'friends#destroy', as: 'set_unfollow'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  delete 'posts/like/delete', to: 'likes#destroyPostLike', as:'post_unlike'
  post 'posts/like/create', to: 'likes#createLikeForPost', as:'post_like'

  post 'comments/like/create', to: 'likes#createLikeForComment', as:'comment_like'
  post 'comments/like/delete', to: 'likes#deleteCommentLike', as:'comment_unlike'

  # Defines the root path route ("/")
  # For group
  get 'groups', to:'groups#show'
  get 'groups/new' , to:'groups#new'
  get 'groups/mygroups' , to:'groups#mygroups'
  post 'groups/new/create' , to:'groups#create', as:'new_group'
  post 'groups/addUser', to:'members#create', as:'add_to_group'
  post 'groups/deleteGroups', to:'groups#delete', as:'delete_group'
  get 'groups/:id/view', to: 'groups#view', as:'view_group'
  get 'groups/join', to: 'groups#join', as:'join_group'



  # get 'groups/mygroups', to:'groups#mygroup'

  root "posts#index"
  resources :likes, only: [:create, :destroy]
  resources :posts do
    resources :comments
  end

  # get 'posts/:postid/comment/:id/', to:'memb'

  resources :users do
    resources :likes
  end
  resources :storys


  # for notifications
    get 'notifications/all', to: 'notifications#view', as:'notifications_all'
    post 'notifications/markasread', to:'notifications#markAsRead', as:'notifications_mark_as_read'



# ``````````````````````````````api start``````````````````````````````````````````````````````
    # For api
    namespace :api ,default: {format: :json} do
      devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For devise

  # devise_for :deviseusers

  # devise_scope :deviceuser do
  #   get '/users', to: 'devise/registrations#new'
  #   get '/users/password', to: 'devise/passwords#new'
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }


 get 'storys', to: 'storys#index'
   delete 'delete/story/:id', to:'storys#delete', as: 'delete_story'
   post 'create/story', to:'storys#create', as:'new_story'
   get 'add/story', to:"storys#new", as:"add_story"

  get 'allusers', to: 'friends#index'
  get 'allusers/following', to: 'friends#following'
  get 'allusers/followers', to: 'friends#followers'
  post 'friends/Following', to: 'friends#create', as: 'set_follow'
  delete 'friends/unFollowing/:id', to: 'friends#destroy', as: 'set_unfollow'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  delete 'posts/like/delete', to: 'likes#destroyPostLike', as:'post_unlike'
  post 'posts/like/create', to: 'likes#createLikeForPost', as:'post_like'

  post 'comments/like/create', to: 'likes#createLikeForComment', as:'comment_like'
  post 'comments/like/delete', to: 'likes#deleteCommentLike', as:'comment_unlike'

  # Defines the root path route ("/")
  # For group
  get 'groups', to:'groups#show'
  post 'groups/new/create' , to:'groups#create', as:'new_group'
  delete 'groups/deleteGroups/:group_id', to:'groups#delete', as:'delete_group'



  # get 'groups/mygroups', to:'groups#mygroup'
  #custom api
  root "posts#index"

  get 'posts/zerolikes', to: 'posts#postWithZeroLike', as:'post_zerolike'
  get 'posts/mostlikes', to: 'posts#postWithMoreLikes', as:'post_mostlike'
  get 'posts/mostComments', to: 'posts#postWithMoreComments', as:'post_mostComments'
  get 'users/morePosts', to:'posts#userWithMorePost', as:'user_morePosts'
  get 'groups/mostgroups', to: 'groups#userWithMoreGroups', as:'user_mostGroups'

  resources :likes, only: [:create, :destroy]
  resources :posts do
    resources :comments
  end

  # get 'posts/:postid/comment/:id/', to:'memb'

  resources :users do
    resources :likes
  end
  resources :storys


  # for notifications
    get 'notifications/all', to: 'notifications#view', as:'notifications_all'
    post 'notifications/markasread', to:'notifications#markAsRead', as:'notifications_mark_as_read'


    end
    # end for api

end

app/models/post.rb
class Post < ApplicationRecord
  paginates_per 3
  validates :title, presence: true,length: { minimum: 2, maximum: 20}
  has_many :comments, dependent: :destroy
  has_many :likes ,as: :likeable ,dependent: :destroy
  validates :description,presence: true,  length: { minimum: 10, maximum: 50}
  has_many_attached :images ,dependent: :destroy
  before_create :randomize_id
  belongs_to :user

  scope :likes_greater_than_one, -> {
    joins("LEFT JOIN (SELECT likeable_id, COUNT(id) AS count_likes FROM likes WHERE likeable_type = 'Post' GROUP BY likeable_id) subquery ON subquery.likeable_id = posts.id")
    .select('posts.*, subquery.count_likes')
    .where('subquery.count_likes > ?', 1)
  }

  scope :with_zero_comments, -> { left_outer_joins(:comments).where(comments: { id: nil }) }



  def post_owner_name
    self.user.name
  end
  private
  def randomize_id

      self.id = SecureRandom.random_number(1_000_000_000)

  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < Api::ApiController

  before_action :is_registered_user, only: [:new,:create,:show, :edit,:update,:destroy]
  before_action :is_post_owner, only: [:edit,:update,:destroy]
  def index
     if current_user
        user = User.find_by(id:current_user.id)
        notification = user.latest_notification
        if notification != nil and notification.hasRead == false
          followedUser = User.find(notification.friend.fromUser)
          flash.now[:notification] = followedUser.name + " is now following you"
        end
     end
    posts = Post.all
    if posts
      if posts.length != 0
        render json: posts, status: :ok
      else
        render json: {message: "no posts" }, status: :ok
      end
    else
       render json: {message:  "posts not available"},status: :not_found
    end
  end

  def show
    post = Post.find_by(id: params[:id])
    if post
      render json: post, status: :found
    else
      render json: {message: "no post found"}, status: :not_found
    end
  end

  def create
    user = User.find_by(id:params[:userId])
    if user
      post = Post.new(post_params)
      user.posts << post
      if post.save
        user.save
        render json: post, status: :created

      else
        render json: {message: post.errors.full_messages}, status: :unprocessable_entity
      end
    else
      render json: {message: "no user found" }, status: :not_found
    end
  end

  def edit

      post = Post.find_by(id:params[:id])
      if post
        render json: post, status: :ok
      else
        render json: {message: "no post found for editing"}, status: :not_found
      end

  end

  def update

      post = Post.find_by(id: params[:id])
      if post
        if post.update(post_params)
            render json: post, status: :ok
        else
          render json: {message: post.errors.full_messages}, status: :unprocessable_entity
        end
      else
        render json: {message: "no post found"}, status: :not_found
      end
  end

  def destroy
    post = Post.find_by(id:params[:id])
    if post
        if post.destroy

          render json: {message:"post deleted" }, status: :see_other

        else
          render json: {message: post.errors.full_messages}, status: :unprocessable_entity
        end
    else
       render json: {message: "no post found"}, status: :not_found
    end
  end
  # custom api
  def postWithZeroLike

    posts_without_likes = Post.left_outer_joins(:likes).where(likes: { id: nil })
    if posts_without_likes
       render json: posts_without_likes,status: :ok
    else
      render json: {message:"unable to fetch"},status: :not_found
    end

  end

  def userWithMorePost
    users_with_many_posts = User.joins(:posts)
                            .group('users.id')
                            .having('COUNT(posts.id) > ?', 1)
                            .order('COUNT(posts.id) DESC')
                             .limit(1)
                            .first
    if users_with_many_posts
       render json: users_with_many_posts,status: :ok
    else
      render json: {message:"unable to fetch"},status: :not_found
    end

  end

  def postWithMoreLikes

   post_with_most_likes = Post.joins(:likes)
                           .group(:id)
                           .order('COUNT(likes.id) DESC')
                           .limit(1)
                           .first
    if post_with_most_likes
       render json: post_with_most_likes,status: :ok
    else
      render json: {message:"unable to fetch"},status: :not_found
    end

  end

  def postWithMoreComments
    post_with_most_comments = Post.joins(:comments)
                              .group(:id)
                              .order('COUNT(comments.id) DESC')
                              .limit(1)
                              .first
    if post_with_most_comments
       render json: post_with_most_comments,status: :ok
    else
      render json: {message:"unable to fetch"},status: :not_found
    end
  end

  private
    def post_params
      # p params[:images]
      params.require(:post).permit(:title, :description,:privacy,:images  )
    end

    def is_post_owner

      post = Post.find_by(id:params[:id])

      unless post and   current_user== post.user
          if post == nil
                render json: {message:"no post found"},status: :not_found
          else
           render json: {message:"only post owner can update or delete"},status: :forbidden
          end
      end

    end
    def is_registered_user
      unless current_user
         render json: {message: "only registered users can access post"} ,status: :unauthorized
      end
   end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, only: [:new,:create,:show, :edit,:update,:destroy]
  before_action :is_post_owner, only: [:edit,:update,:destroy]
  def index
     if user_signed_in?
        user = User.find_by(id:current_user.id)
        notification = user.latest_notification
        if notification != nil and notification.hasRead == false
          followedUser = User.find(notification.friend.fromUser)
          flash.now[:notification] = followedUser.name + " is now following you"
        end
     end

    allposts = Post.all

    @flag = false
    unless params[:field]
      p 'gfhj1````````````'
        @flag = true
        @posts=Post.includes(:user,:likes,:comments).page(params[:page])
    else
        @posts = Array.new
        allposts.each do |post|
            @posts.push(post)
        end
        if  params[:field] and params[:field] == "Name" and params[:value].length!=0
          @posts = filter_posts_by_user_name(Post.all, /^#{params[:value]}/)
        end
        if  params[:field] and params[:field] == "Title" and params[:value].length!=0
          @posts = @posts.select{ |post| post[:title] =~ /#{params[:value]}/ }
          p '````````21'
          p @posts
        end
        if  params[:field] and params[:field] == "Description" and params[:value].length!=0
          @posts =  @posts.select{ |post| post[:description] =~ /#{params[:value]}/ }
        end
    end
  end

  def show
    @post = Post.find(params[:id])
  end
  def new
    @post = Post.new
  end
  def create
    @user = User.find(current_user.id)
    @post = Post.new(post_params)
    @user.posts << @post
    if @post.save

      @user.save
      redirect_to  posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update

    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to  posts_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy

    @post = Post.find_by(id:params[:id])

    if  @post != nil and @post.destroy
      redirect_to root_path, status: :see_other
    else
      redirect_to root_path, notice:"unable to destroy.."
    end


  end

  private
    def post_params
      params.require(:post).permit(:title, :description,:privacy, images:[])
    end
    def is_post_owner
      @post = Post.find_by(id:params[:id])
      unless @post and user_signed_in? and current_user.id == @post.user.id
          flash[:notice] = "Unauthorized access"
          redirect_to root_path
      end
    end
    def filter_posts_by_user_name(posts, pattern)
      posts.select { |post| post.user.name =~ pattern }
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% stylesheet_link_tag "postsForm"%>

<div class="newPost">

<%= form_with class:"form-group newPostForm bg-light text-dark", model: post  do |form| %>

  <div class="mb-3">
    <label for="title" class="form-label">Title</label>
    <%= form.text_field :title , class:"form-control" %>
  </div>
  <% post.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  <div>
    <label for="description" class="form-label">Description</label>
    <%= form.text_area :description ,class:"form-control" %>
  </div>
  <div>
    <br>
     <label for="Category" class="form-label">Post category</label>
    <%= form.select :privacy, options_for_select([['Public', 'Public'], ['Private', 'Private'] ]), include_blank: false %>
</div>

<% post.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  <div>
    <br>
     <%= form.file_field :images, multiple:true%>

  </div>
  <div class="mb-3">
     <br>
   <%= form.submit class: "btn btn-success w-100" %>
   </div>
<% end %>

</div>

app/views/posts/edit.html.erb
<br>
<h1>EDIT POST </h1>
<br>
<%= render "form", post: @post %>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'postsIndex' %>




<div class="row postParent bg-light" >




<% @posts.each do |post| %>

<%# Checking for privacy %>
<%if user_signed_in? == false and post.privacy=="Private"%>

<% next %>

<% end %>

<% if user_signed_in? and post.privacy == "Private" and  post.user.id != current_user.id%>


<% friend = Friend.where(fromUser: post.user.id, toUser: current_user.id,followed: true )  %>

  <% if friend.length == 0 %>

      <% next%>
  <% end %>
<% end %>


<div class ="row" style="justify-content:center">
<div class="card mb-3 col-md-6   text-dark">
  <div class="card-header row">
    <h5 class="card-title col-md-6">
            <i class="fa-solid fa-user  "></i>

             <%= post.post_owner_name%></h5>
    <h5 class="card-title col-md-6 ">
 <%= link_to   post do %>
 <button type="button" class="btn btn-primary float-md-end">View</button>

 <%end%>
  </h5>

  </div>
  <div class="card-body">
    <h6 class="card-subtitle mb-2 text-muted"><%= post.title%></h6>


      <% post.images.each do |image|%>

      <%= image_tag(image ,class:'img-fluid' )%>
     <%end%>

    <p class="card-text"><%= post.description%></p>
    <hr>
    <div class="d-flex flex-row" >
      <% if user_signed_in? %>
        <% like = post.likes.where(user_id:current_user.id)%>
          <% if like.length == 0%>
              <%= button_to post_like_path, params: {post_id: post.id}, class:"likesButton",method: :post, class:'likesButton'  do %>
              <i class="fa-regular fa-heart likUnlikeIcon"></i>
              <%end%>
          <%else%>

              <%= button_to   post_unlike_path, params: {post_id: post.id, like_id: like[0].id }, method: :delete, class:'likesButton'   do %>
              <i class="fa-solid fa-heart likUnlikeIcon"></i>
              <%end%>
          <% end %>
        <% else %>
            <%= button_to post_like_path, params: {post_id: post.id}, class:"likesButton",method: :post, class:'likesButton'  do %>
              <i class="fa-regular fa-heart likUnlikeIcon"></i>
              <%end%>

      <% end %>
        <div class="post-info">
          <span class="likes-count"><i class="bi bi-heart-fill"></i> <%= post.likes.count %> Likes</span>
          <span class="comment-count"><i class="bi bi-chat-fill"></i>  <%= post.comments.count %> Comments</span>
        </div>
      </div>
  </div>

</div>




<%# ```````````````````````````` %>

<% if false %>

<div class ="row" style="justify-content:center">
<div class="col-md-6" >
    <h1>Title:</h1>

    <p> <%= post.title %><p>
    <h1>Description:</h1>

    <p> <%= post.description %><p>
    <%= link_to "View Post", post %>
    <p>

    <% post.images.each do |image|%>

      <%= image_tag(image, style: "object-fit: contain; width: 200px; height: 200px") %>


    <%end%>
  </p>
  <%= like = post.likes.where(user_id:1)%>

  <% if like.length == 0%>
  <%= button_to "like", post_like_path, params: {post_id: post.id}, method: :post %>
  <%else%>
  <%= like[0].id%>
   <%= button_to "UNlike", post_unlike_path, params: {post_id: post.id, like_id: like[0].id }, method: :post %>

  <% end %>

    LIKES:  <%= post.likes.count %>
    COMMENTS: <%= post.comments.count%>
    <hr>
</div>
</div>

<%end%>
<%# for if false %>

<%end %>
<% if @flag %>
<%= paginate @posts %>
<% end %>
</div>

app/views/posts/new.html.erb
<div class="d-flex justify-content-center">

 <div class="col-md-6 ">
    <br>
    <h1>New Post</h1>
<%= render "form", post: @post %>

</div>

</div>

app/views/posts/show.html.erb
 <%= stylesheet_link_tag 'postsShow' %> <div class="row" style="justify-content:center">
    <div class="card mb-3 col-md-6 ">
        <div class="card-header row">
            <h5 class="card-title col-md-6 postUserName">
                <i class="fa-solid fa-user  "></i>
                <span class="userName"> <%= @post.user.name%>
            </h5>
            </span>
            <h5 class="card-title col-md-6 ">
                <% if user_signed_in? and current_user.id == @post.user.id %>
                  <div class="d-flex justify-content-end">
                      <div style="margin-right:5px"> <%= link_to  edit_post_path(@post), class:"editDelete" do%> <button class="btn btn-sm btn-primary"> EDIT</button> <%end%> </div>
                      <div> <%= link_to  post_path(@post),class:"editDelete", data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    } do %> <button class="btn btn-sm btn-danger"> DELETE</button> <%end%> </div>
                  </div>
                <% end %>
            </h5>
        </div>
        <div class="card-body">
            <h6 class="card-subtitle mb-2 text-muted"><%= @post.title%></h6> <% @post.images.each do |image|%> <%= image_tag(image ,class:'img-fluid' )%> <%end%> <p class="card-text"><%= @post.description%></p>
            <div class="d-flex flex-row"> <% like = @post.likes.where(user_id:1)%> <% if like.length == 0%> <%= button_to post_like_path, params: {post_id: @post.id}, class:"likesButton",method: :post, class:'likesButton'  do %> <i class="fa-regular fa-heart likUnlikeIcon"></i> <%end%> <%else%> <%= button_to   post_unlike_path, params: {post_id: @post.id, like_id: like[0].id }, method: :post, class:'likesButton'   do %> <i class="fa-solid fa-heart likUnlikeIcon"></i> <%end%> <% end %> <div class="post-info">
                    <span class="likes-count"><i class="bi bi-heart-fill"></i> <%= @post.likes.count %> Likes</span>
                    <span class="comment-count"><i class="bi bi-chat-fill"></i> <%= @post.comments.count %> Comments</span>
                </div>
            </div>
            <hr>
            <div> <%= render "comments/form", post: @post %> </div>
            <div class="row Allcomments">
                <div class="row AllcommentsRow1"> All comments </div>
                <div class="d-flex flex-column AllcommentsRow2"> <%= render "comments/show", post: @post %> </div>
            </div> <%# ```````````````````````````` %> <% if false %>
            <hr> New Comment <%= render "comments/form", post: @post %> <div> <%= link_to  edit_post_path(@post), class:"editDelete" do%> <button class="btn btn-sm btn-primary"> EDIT</button> <%end%> <%= link_to  post_path(@post),class:"editDelete", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } do %> <button class="btn btn-sm btn-danger"> DELETE</button> <%end%> </div> <% end %>