config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For devise

  # devise_for :deviseusers

  # devise_scope :deviceuser do
  #   get '/users', to: 'devise/registrations#new'
  #   get '/users/password', to: 'devise/passwords#new'
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }


 get 'storys', to: 'storys#index'
   delete 'delete/story', to:'storys#delete', as: 'delete_story'
   post 'create/story', to:'storys#create', as:'new_story'
   get 'add/story', to:"storys#new", as:"add_story"

  get 'allusers', to: 'friends#index'
  get 'allusers/following', to: 'friends#following'
  get 'allusers/followers', to: 'friends#followers'
  post 'friends/Following', to: 'friends#create', as: 'set_follow'
    delete 'friends/unFollowing', to: 'friends#destroy', as: 'set_unfollow'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  delete 'posts/like/delete', to: 'likes#destroyPostLike', as:'post_unlike'
  post 'posts/like/create', to: 'likes#createLikeForPost', as:'post_like'

  post 'comments/like/create', to: 'likes#createLikeForComment', as:'comment_like'
  post 'comments/like/delete', to: 'likes#deleteCommentLike', as:'comment_unlike'

  # Defines the root path route ("/")
  # For group
  get 'groups', to:'groups#show'
  get 'groups/new' , to:'groups#new'
  get 'groups/mygroups' , to:'groups#mygroups'
  post 'groups/new/create' , to:'groups#create', as:'new_group'
  post 'groups/addUser', to:'members#create', as:'add_to_group'
  post 'groups/deleteGroups', to:'groups#delete', as:'delete_group'
  get 'groups/:id/view', to: 'groups#view', as:'view_group'
  get 'groups/join', to: 'groups#join', as:'join_group'



  # get 'groups/mygroups', to:'groups#mygroup'

  root "posts#index"
  resources :likes, only: [:create, :destroy]
  resources :posts do
    resources :comments
  end

  # get 'posts/:postid/comment/:id/', to:'memb'

  resources :users do
    resources :likes
  end
  resources :storys


  # for notifications
    get 'notifications/all', to: 'notifications#view', as:'notifications_all'
    post 'notifications/markasread', to:'notifications#markAsRead', as:'notifications_mark_as_read'



# ``````````````````````````````api start``````````````````````````````````````````````````````
    # For api
    namespace :api ,default: {format: :json} do
      devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For devise

  # devise_for :deviseusers

  # devise_scope :deviceuser do
  #   get '/users', to: 'devise/registrations#new'
  #   get '/users/password', to: 'devise/passwords#new'
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }


 get 'storys', to: 'storys#index'
   delete 'delete/story/:id', to:'storys#delete', as: 'delete_story'
   post 'create/story', to:'storys#create', as:'new_story'
   get 'add/story', to:"storys#new", as:"add_story"

  get 'allusers', to: 'friends#index'
  get 'allusers/following', to: 'friends#following'
  get 'allusers/followers', to: 'friends#followers'
  post 'friends/Following', to: 'friends#create', as: 'set_follow'
  delete 'friends/unFollowing/:id', to: 'friends#destroy', as: 'set_unfollow'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  delete 'posts/like/delete', to: 'likes#destroyPostLike', as:'post_unlike'
  post 'posts/like/create', to: 'likes#createLikeForPost', as:'post_like'

  post 'comments/like/create', to: 'likes#createLikeForComment', as:'comment_like'
  post 'comments/like/delete', to: 'likes#deleteCommentLike', as:'comment_unlike'

  # Defines the root path route ("/")
  # For group
  get 'groups', to:'groups#show'
  post 'groups/new/create' , to:'groups#create', as:'new_group'
  delete 'groups/deleteGroups/:group_id', to:'groups#delete', as:'delete_group'



  # get 'groups/mygroups', to:'groups#mygroup'
  #custom api
  root "posts#index"

  get 'posts/zerolikes', to: 'posts#postWithZeroLike', as:'post_zerolike'
  get 'posts/mostlikes', to: 'posts#postWithMoreLikes', as:'post_mostlike'
  get 'posts/mostComments', to: 'posts#postWithMoreComments', as:'post_mostComments'
  get 'users/morePosts', to:'posts#userWithMorePost', as:'user_morePosts'
  get 'groups/mostgroups', to: 'groups#userWithMoreGroups', as:'user_mostGroups'

  resources :likes, only: [:create, :destroy]
  resources :posts do
    resources :comments
  end

  # get 'posts/:postid/comment/:id/', to:'memb'

  resources :users do
    resources :likes
  end
  resources :storys


  # for notifications
    get 'notifications/all', to: 'notifications#view', as:'notifications_all'
    post 'notifications/markasread', to:'notifications#markAsRead', as:'notifications_mark_as_read'


    end
    # end for api

end

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag 'navbar' %>

<nav class="navbar navbar-expand-lg navbar-dark navbarCustom">


    <a class="navbar-brand" href="#">SociaGram</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
           <%= link_to "Home", root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
             <%= link_to "New Post", new_post_path, class: 'nav-link' %>
        </li>
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Groups
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
             <li class="dropdown-item">
                 <%= link_to "All groups", groups_path, class: 'dropdown-item' %>
             </li>

            <li><hr class="dropdown-divider"></li>
              <li class="dropdown-item">
                 <%= link_to "Create Group",groups_new_path, class: 'dropdown-item' %>
              </li>
              <li class="dropdown-item">
                 <%= link_to "My Groups",groups_mygroups_path, class: 'dropdown-item' %>
              </li>
          </ul>
        </li>


       <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Peoples
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
             <li class="dropdown-item">
                 <%= link_to "All People", allusers_path, class: 'dropdown-item' %>
              </li>

            <li><hr class="dropdown-divider"></li>
            <li class="dropdown-item">
                 <%= link_to "Following", allusers_following_path, class: 'dropdown-item' %>
            </li>
            <li class="dropdown-item">
                 <%= link_to "Followers", allusers_followers_path, class: 'dropdown-item' %>
            </li>
          </ul>
        </li>


        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Story
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
             <li class="dropdown-item">
                 <%= link_to "Story", storys_path, class: 'dropdown-item' %>
              </li>

              <li><hr class="dropdown-divider"></li>
            <li class="dropdown-item">
                 <%= link_to "Add Your Story", add_story_path, class: 'dropdown-item' %>
              </li>
          </ul>
        </li>


        <% if  user_signed_in? %>

              <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa-solid fa-user  "></i><%= current_user.name%>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
             <li class="nav-item">
              <%= button_to "SigOut", destroy_user_session_path, method: :delete, class: 'dropdown-item btn'  %>
            </li>
             <li class="nav-item">
               <%= link_to "Edit", edit_user_registration_path , class: 'dropdown-item'%>
            </li>

          </ul>
        </li>

        <% else %>
            <li class="nav-item">
              <%= link_to "Signup", new_user_registration_path, class: 'nav-link' %>
            </li>
        <% end %>

        <li class="nav-item">
                 <%= link_to "My notifications", notifications_all_path, class: 'nav-link' %>
        </li>



      </ul>

      <ul class="navbar-nav mx-3">

        <%=form_with url:root_path ,class:"d-flex flex-row gap-2"   ,method: :get do |f|%>
           <li class="form-group   nav-item">
                    <%=f.text_field :value ,class:"form-control",placeholder:"Search by" %>
           </li>
            <li class="form-group  nav-item ">
                  <%= f.select(:field,[['Title', 'Title'], ['Description', 'Description'], ['Name', 'Name'] ],{},{:class=>"form-select"})%>
           </li>
            <li class="form-group nav-item ">
                   <%= button_tag type: :submit, class:"commentSubmit btn btn-primary "  do %>
                               Search
                   <% end %>
           </li>
        <%end%>
      </ul>


  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Socialmedia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag "favicon.png"%>

    <%# For Bootstrap %>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

    <%# For google fonts %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@1,300&display=swap" rel="stylesheet">

<%# google icons %>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

<%# For font awesome %>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<style>
  body{
    font-family: 'Lato', sans-serif;
  font-weight: 800;


  }
  .flashing{
    background-color: grey;
  }
  </style>
 </head>

  <body class="container-fluid" id="background">

      <div class="row">
      <%= render 'layouts/navbar' ,class: 'row'%>

      </div>

    <% if flash[:notice] %>
          <div class="alert alert-warning alert-dismissible fade show w-50" role="alert" style="margin-left:25%;margin-top:2%;">
                  <%= flash[:notice] %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
    <% end %>
    <% if flash[:notification] %>
          <div class="alert alert-warning alert-dismissible fade show w-50" role="alert" style="margin-left:25%;margin-top:2%;">
                  <%= flash[:notification] %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
    <% end %>
     <% if flash[:error] %>
          <div class="alert alert-warning alert-dismissible fade show w-50" role="alert" style="margin-left:25%;margin-top:2%;">
                  <%= flash[:error] %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
    <% end %>
    <%= yield %>


  </body>
</html>